# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final',
            name='class_day',
            field=models.CharField(choices=[('Monday, Tuesday, Wednesday', 'MTW'), ('Tuesday, Thursday', 'TR')], default='Monday, Tuesday, Wednesday', max_length=50),
        ),
    ]
