# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finals', '0003_auto_20170727_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final',
            name='class_day',
            field=models.CharField(choices=[('MTW', 'Monday, Tuesday, Wednesday'), ('TR', 'Tuesday, Thursday')], default='MTW', max_length=100),
        ),
    ]
