# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finals', '0005_auto_20170727_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final',
            name='class_time',
            field=models.TimeField(),
        ),
    ]
