# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finals', '0007_auto_20170728_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final',
            name='final_info',
            field=models.CharField(max_length=100),
        ),
    ]
