# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finals', '0008_auto_20170728_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='final',
            name='class_timeframe',
            field=models.CharField(choices=[('a.m.', 'AM'), ('p.m.', 'PM')], default='a.m.', max_length=100),
        ),
    ]
